### ISSUE TITLE
Better handling of exceptions / CPU load

### ISSUE THREAD

**Issue by MrDefacto** [nmarley/sentinel#22]
Hi,

Some errors because of high CPU load... Execution time about 40 seconds. So there are some too short timeouts.

```
 Traceback (most recent call last):
   File "/sentinel/scripts/crontab.py", line 181, in <module>
     main()
   File "/sentinel/scripts/crontab.py", line 152, in main
     watchdog_check(dashd)
   File "/sentinel/scripts/crontab.py", line 26, in watchdog_check
     for wd in Watchdog.expired(dashd):
   File "/sentinel/scripts/../lib/models.py", line 553, in expired
     self.created_at < (now - dashd.SENTINEL_WATCHDOG_MAX_SECONDS)
   File "/sentinel/scripts/../lib/dashd.py", line 199, in SENTINEL_WATCHDOG_MAX_SECONDS
     return (self.MASTERNODE_WATCHDOG_MAX_SECONDS // 2)
   File "/sentinel/scripts/../lib/dashd.py", line 195, in MASTERNODE_WATCHDOG_MAX_SECONDS
     return self.govinfo['masternodewatchdogmaxseconds']
   File "/sentinel/scripts/../lib/dashd.py", line 83, in govinfo
     self.governance_info = self.rpc_command('getgovernanceinfo')
   File "/sentinel/scripts/../lib/dashd.py", line 41, in rpc_command
     return self.rpc_connection.__getattr__(params[0])(*params[1:])
   File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 139, in __call__
     response = self._get_response()
   File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 179, in _get_response
     http_response = self.__conn.getresponse()
   File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
     response.begin()
   File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
     version, status, reason = self._read_status()
   File "/usr/local/lib/python2.7/httplib.py", line 402, in _read_status
     raise BadStatusLine(line)
 httplib.BadStatusLine: ''


 Traceback (most recent call last):
   File "/sentinel/scripts/crontab.py", line 181, in <module>
     main()
   File "/sentinel/scripts/crontab.py", line 152, in main
     watchdog_check(dashd)
   File "/sentinel/scripts/crontab.py", line 26, in watchdog_check
     for wd in Watchdog.expired(dashd):
   File "/sentinel/scripts/../lib/models.py", line 553, in expired
     self.created_at < (now - dashd.SENTINEL_WATCHDOG_MAX_SECONDS)
   File "/sentinel/scripts/../lib/dashd.py", line 199, in SENTINEL_WATCHDOG_MAX_SECONDS
     return (self.MASTERNODE_WATCHDOG_MAX_SECONDS // 2)
   File "/sentinel/scripts/../lib/dashd.py", line 195, in MASTERNODE_WATCHDOG_MAX_SECONDS
     return self.govinfo['masternodewatchdogmaxseconds']
   File "/sentinel/scripts/../lib/dashd.py", line 83, in govinfo
     self.governance_info = self.rpc_command('getgovernanceinfo')
   File "/sentinel/scripts/../lib/dashd.py", line 41, in rpc_command
     return self.rpc_connection.__getattr__(params[0])(*params[1:])
   File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 139, in __call__
     response = self._get_response()
   File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 179, in _get_response
     http_response = self.__conn.getresponse()
   File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
     response.begin()
   File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
     version, status, reason = self._read_status()
   File "/usr/local/lib/python2.7/httplib.py", line 394, in _read_status
     line = self.fp.readline(_MAXLINE + 1)
   File "/usr/local/lib/python2.7/socket.py", line 480, in readline
     data = self._sock.recv(self._rbufsize)
 socket.error: [Errno 54] Connection reset by peer

```

**Comment by nmarley** [comment]
Thanks for reporting. We're aware of this, and it's actually a timeout set on the DashCore software -- raising the Sentinel timeout will not change anything until the DashCore software is updated.

https://github.com/dashpay/dash/blob/v0.12.1.x/src/httpserver.h#L16
