### ISSUE TITLE
every couple sentinel runs there is error

### ISSUE THREAD

**Issue by MrDefacto** [nmarley/sentinel#25]
Hi, 

Error:

```
Traceback (most recent call last):
   File "/sentinel/scripts/crontab.py", line 188, in <module>
     main()
   File "/sentinel/scripts/crontab.py", line 159, in main
     watchdog_check(dashd)
   File "/sentinel/scripts/crontab.py", line 26, in watchdog_check
     for wd in Watchdog.expired(dashd):
   File "/sentinel/scripts/../lib/models.py", line 556, in expired
     self.created_at < (now - dashd.SENTINEL_WATCHDOG_MAX_SECONDS)
   File "/sentinel/scripts/../lib/dashd.py", line 199, in SENTINEL_WATCHDOG_MAX_SECONDS
     return (self.MASTERNODE_WATCHDOG_MAX_SECONDS // 2)
   File "/sentinel/scripts/../lib/dashd.py", line 195, in MASTERNODE_WATCHDOG_MAX_SECONDS
     return self.govinfo['masternodewatchdogmaxseconds']
   File "/sentinel/scripts/../lib/dashd.py", line 83, in govinfo
     self.governance_info = self.rpc_command('getgovernanceinfo')
   File "/sentinel/scripts/../lib/dashd.py", line 41, in rpc_command
     return self.rpc_connection.__getattr__(params[0])(*params[1:])
   File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 139, in __call__
     response = self._get_response()
   File "/usr/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 179, in _get_response
     http_response = self.__conn.getresponse()
   File "/usr/local/lib/python2.7/httplib.py", line 1121, in getresponse
     response.begin()
   File "/usr/local/lib/python2.7/httplib.py", line 438, in begin
     version, status, reason = self._read_status()
   File "/usr/local/lib/python2.7/httplib.py", line 402, in _read_status
     raise BadStatusLine(line)
 httplib.BadStatusLine: ''
```

Today latest version from github. But this error also shows up yeasterday.

**Comment by nmarley** [comment]
Hi,

* What version of Sentinel are you running?
* What is the output of `dash-cli gobject count` on your system?

**Comment by MrDefacto** [comment]
current. From today. 

Governance Objects: 1335 (Proposals: 1279, Triggers: 55, Watchdogs: 1, Other: 0; Seen: 2285), Votes: 322661
Governance Objects: 1349 (Proposals: 1279, Triggers: 55, Watchdogs: 15, Other: 0; Seen: 2267), Votes: 323164
Governance Objects: 1367 (Proposals: 1275, Triggers: 91, Watchdogs: 1, Other: 0; Seen: 2063), Votes: 309018

**Comment by nmarley** [comment]
> current. From today.

Can you provide a commit hash? There are a couple of commits it could have been from today. Also, the concept of "today" is relative, as you might be in another time zone than me.

**Comment by MrDefacto** [comment]
commit 9b66e90611e0e768b57d4a84f9e4fe5d0431a6f2
Author: Nathan Marley <nathan.marley@gmail.com>
Date:   Wed Jan 25 16:41:15 2017 -0800

    pg-13 comments

**Comment by nmarley** [comment]
Commit dc2f66be273ce55a389c2914e9669396c8307bf4 introduced a change to not re-use http/jsonrpc connections, which should help resolve these issues you're seeing. Can you please update to at least that version (preferably the latest master) and report back on whether you're still seeing these errors?

**Comment by MrDefacto** [comment]
Updated 2 hours after your commit :-) already testing :-D

**Comment by nmarley** [comment]
Closing as no further issues after dc2f66b, which should likely have fixed this.
