### ISSUE TITLE
NoneType object traceback

### ISSUE THREAD

**Issue by taw00** [nmarley/sentinel#9]
Haven't dug into the code yet, but...

```
govobj updated = 1
subobj updated = 1
govobj updated = 1
subobj updated = 1
in watchdog_check
	Found expired watchdog [dbab176b3a970df7c457633afe9365985c18ebe5df3b0c001ed0de6169aaf827], voting to delete
Found a vote for this gobject/signal...
Already voted for this same gobject/signal/outcome, no need to re-vote.
	Found expired watchdog [d647a0cfb29e53364dcac4ac07f75f313093aefdb9668e30bbf28dbdf337191a], voting to delete
Haven't voted on this gobject/signal yet...
gobject vote-conf d647a0cfb29e53364dcac4ac07f75f313093aefdb9668e30bbf28dbdf337191a delete yes
result  = [failed]
err_msg = [Can't find masternode by collateral output]
VOTE failed, trying to sync with network vote
	syncing network vote for object d647a0cfb29e53364dcac4ac07f75f313093aefdb9668e30bbf28dbdf337191a with signal delete
Traceback (most recent call last):
  File "scripts/crontab.py", line 174, in <module>
    main()
  File "scripts/crontab.py", line 151, in main
    watchdog_check(dashd)
  File "scripts/crontab.py", line 27, in watchdog_check
    wd.vote(dashd, VoteSignals.delete, VoteOutcomes.yes)
  File "scripts/../lib/governance_class.py", line 24, in vote
    return self.go.vote(dashd, signal, outcome)
  File "scripts/../lib/models.py", line 188, in vote
    self.sync_network_vote(dashd, signal)
  File "scripts/../lib/models.py", line 192, in sync_network_vote
    vote_info = dashd.get_my_gobject_votes(self.object_hash)
  File "scripts/../lib/dashd.py", line 139, in get_my_gobject_votes
    (txid, vout_index) = my_vin.split('-')
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by nmarley** [comment]
Thanks for reporting! Fixed in 41eb3665ffeb9254d77938a0a2424f131d25ce86
